version: "3.8"

services:
  akdot_react:
    container_name: akdot_react_container
    build:
      context: ./react-ui
      dockerfile: Dockerfile
    image: akdot_react
    ports:
      - "80:3000"
    #environment:
    #  - HOST_URL=${HOST}
    #networks:
    #  - local-ai
  
  akdot_flask:
    build:
      context: ./flask-server
      dockerfile: Dockerfile
    container_name: akdot_flask_container
    image: akdot_flask
    restart: always
    ports:
      - "7001:7001"
    #networks:
      #- local-ai
    # volumes:
    #   - ./flask-server/staging:/flask-server/staging

#volumes:
#  user_storage: {}

#networks:
#  local-ai:
  
